[versions]
activity-compose = "1.7.2"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "33"
android-crypto = "1.1.0-alpha06"
androidx-test = "1.5.0"
androidx-test-runner = "1.5.2"
androidx-test-ext = "1.1.5"
biometric = "1.2.0-alpha05"
compose-compiler = "1.5.3"
compose-bom = "2023.09.00"
coroutines = "1.7.3"
dropbox-core = "5.4.5"
agp = "8.0.2"
detekt = "1.23.0"
versions-ben-manes = "0.48.0"
java = "11"
junit = "4.13.2"
kermit = "1.2.2"
koin-core = "3.4.2"
koin-android = "3.4.2"
koin-androidx-compose = "3.4.5"
koin-test = "3.4.1"
kotlin = "1.9.10"
kotlinx-date-time = "0.4.1"
multiplatform-settings = "1.0.0"
nav-compose = "2.7.1"
paging-compose = "1.0.0-alpha20"
sqlDelight = "1.5.5"
timber = "5.0.1"
turbine = "1.0.0"
viewModel-ktx = "2.6.1"

[libraries]
androidx-activity-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-biometric-ktx = { module = "androidx.biometric:biometric-ktx", version.ref = "biometric" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-lifecycle-viewModel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "viewModel-ktx" }
androidx-navigation-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "nav-compose" }
androidx-paging-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-compose" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "android-crypto" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
cashapp-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
dropbox-core = { module = "com.dropbox.core:dropbox-core-sdk", version.ref = "dropbox-core" }
jake-timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-androidx-compose" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-core" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin-test" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutine-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-date-time" }
russhwolf-multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
russhwolf-multiplatform-settings-test = { module = "com.russhwolf:multiplatform-settings-test", version.ref = "multiplatform-settings" }
squareup-sqldelight-android-driver = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
squareup-sqldelight-coroutine-extensions = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
squareup-sqldelight-native-driver = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqlDelight" }
squareup-sqldelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqlDelight" }
squareup-sqldelight-sqlite-driver = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
touchlab-kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
io-gitlab-arturbosch-detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[bundles]
androidx-test = ["androidx-test-core", "androidx-test-ext-junit", "androidx-test-rules", "androidx-test-runner"]
compose = ["androidx-activity-activity-compose", "androidx-compose-foundation", "androidx-compose-material", "androidx-compose-material-icons-core", "androidx-compose-material-icons-extended", "androidx-compose-runtime", "androidx-compose-ui", "androidx-compose-ui-ui-test", "androidx-compose-ui-ui-tooling", "androidx-navigation-navigation-compose", "androidx-paging-paging-compose"]
koin = ["koin-android", "koin-androidx-compose", "koin-core"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
versionsBenManes = { id = "com.github.ben-manes.versions", version.ref = "versions-ben-manes" }
touchlab-kermit = { id = "co.touchlab.kermit", version.ref = "kermit" }
sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqlDelight" }
